// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TicketManagementSystem_CAA.Models;

public partial class Admin
{
    public int AId { get; set; }

    public string Adminname { get; set; }

    public string Email { get; set; }

    public string Cnic { get; set; }

    public int? DId { get; set; }

    public string Mobileno { get; set; }

    public string Password { get; set; }

    public string Role { get; set; }

    public DateTime? DateDeleted { get; set; }

    public virtual Department DIdNavigation { get; set; }

    public virtual ICollection<ProgressNotification> ProgressNotifications { get; set; } = new List<ProgressNotification>();

    public virtual ICollection<TicketResponse> TicketResponses { get; set; } = new List<TicketResponse>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}