// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TicketManagementSystem_CAA.Models;

public partial class Feedback
{
    public int Id { get; set; }

    public int TicketId { get; set; }

    public string Feedback1 { get; set; }

    public string Comments { get; set; }

    public DateTime? DateTime { get; set; }

    public virtual Ticket Ticket { get; set; }
}