// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TicketManagementSystem_CAA.Models;

namespace TicketManagementSystem_CAA.Models
{
    public partial interface ItmsContextProcedures
    {
        Task<int> SoftDeleteUserAsync(int? UserID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
