// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TicketManagementSystem_CAA.Models;

public partial class Notification
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public DateTime Timestamp { get; set; }

    public bool IsRead { get; set; }

    public int? TicketId { get; set; }

    public virtual Ticket Ticket { get; set; }

    public virtual Users1 User { get; set; }
}