// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TicketManagementSystem_CAA.Models;

public partial class ProgressNotification
{
    public int Id { get; set; }

    public int AdminId { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public DateTime Timestamp { get; set; }

    public bool IsRead { get; set; }

    public virtual Admin Admin { get; set; }
}