// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TicketManagementSystem_CAA.Models;

public partial class Severitylvl
{
    public int Lvlid { get; set; }

    public string Sdesc { get; set; }

    public string Ldesc { get; set; }

    public DateTime? DateDeleted { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}