// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TicketManagementSystem_CAA.Models;

public partial class Ticket
{
    public int TId { get; set; }

    public string TTitle { get; set; }

    public int? UId { get; set; }

    public int? Lvlid { get; set; }

    public int? SId { get; set; }

    public DateTime? DateTime { get; set; }

    public string LDescription { get; set; }

    public DateTime? DateDeleted { get; set; }

    public string Reason { get; set; }

    public int? AssignedToDepartment { get; set; }

    public int? AssignedToAdmin { get; set; }

    public virtual Admin AssignedToAdminNavigation { get; set; }

    public virtual Department AssignedToDepartmentNavigation { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual Severitylvl Lvl { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual Tstatus SIdNavigation { get; set; }

    public virtual ICollection<TicketResponse> TicketResponses { get; set; } = new List<TicketResponse>();

    public virtual Users1 UIdNavigation { get; set; }
}