// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TicketManagementSystem_CAA.Models;

public partial class TicketResponse
{
    public int Id { get; set; }

    public int? TId { get; set; }

    public string RBody { get; set; }

    public int? AId { get; set; }

    public int? UId { get; set; }

    public int? DId { get; set; }

    public DateTime? DateTime { get; set; }

    public int? SId { get; set; }

    public string Role { get; set; }

    public virtual Admin AIdNavigation { get; set; }

    public virtual Department DIdNavigation { get; set; }

    public virtual Tstatus SIdNavigation { get; set; }

    public virtual Ticket TIdNavigation { get; set; }

    public virtual Users1 UIdNavigation { get; set; }
}