// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TicketManagementSystem_CAA.Models;

public partial class Users1
{
    public int Uid { get; set; }

    public string Username { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string Province { get; set; }

    public string Email { get; set; }

    public string Cnic { get; set; }

    public long? Mobileno { get; set; }

    public string Password { get; set; }

    public DateTime? DateDeleted { get; set; }

    public byte[] Picture { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<TicketResponse> TicketResponses { get; set; } = new List<TicketResponse>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}